apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # santiagoroot@gmail.com
  # estoesunaclaveprivada
  PG_USER_EMAIL: c2FudGlhZ29yb290QGdtYWlsLmNvbQ==
  PG_USER_PASSWORD: ZXN0b2VzdW5hY2xhdmVwcml2YWRh